name: 診療内科クリニック
postal-code: 〒123-0000
address: 東京都某区某町１－２－３
tel: 03-0000-0000
fax: 03-0000-0000
todoufukencode: 13
tensuuhyoucode: 1
kikancode: 1234567
homepage: https://example.com
doctor-name: 診療太郎
