users:
  - id: Practice
    name: 診察
  - id: Reception
    name: 受付
presetMessages:
  Practice:
    - "おはようございます。"
    - "診察室におねがいします。"
    - "処方箋おねがいします。"
  Reception:
    - "おはようございます。"
    - "退出します。"
    - "戻りました。"
    - "検温中です。"
    - "体温 {} 度でした。"
    - "胃腸の調子が悪いそうです。"
    - "相談です。"
    - "セットできました。"
    - "お薬手帳忘れです。"
    - "面会の方いらしてます。"
