chronic:
  - 高血圧症
  - 高脂血症
  - 糖尿病
  - 甲状腺機能低下症
  - 甲状腺機能亢進症
  - 虚血性心疾患
  - 心房細動
  - うっ血性心不全
  - 虚血性脳血管障害
  - 単純性慢性気管支炎
  - 気管支拡張症
  - 肺気腫
  - 気管支喘息
  - 慢性肝炎
  - 慢性ウイルス肝炎
  - 慢性膵炎
chronicDrug:
  - アムロジピン
  - ニフェジピン
  - ベニジピン
  - アダラート
  - カルブロック
  - ミカルディス
  - カンデサルタン
  - レニベース
  - フルイトラン
  - ロサルタン
  - ディオバン
  - イルアミクス
  - アトルバスタチン
  - プラバスタチン
  - リピトール
  - ゼチーア
  - グリメピリド
  - ジャヌビア
  - メトグルコ
  - チラーヂン
  - プラザキサ
  - アドエア
  - スピリーバ
  - フルティフォーム


